apiVersion: v1
kind: ConfigMap
metadata:
  name: urls-env-config-private
data:
  constants.ini: |
    CHATBOT_RUUTER_PUBLIC=http://component-byk-ruuter:8080
    CHATBOT_RUUTER_PRIVATE=http://component-byk-ruuter-private:8080
    CHATBOT_RUUTER=http://component-byk-ruuter:8080
    CHATBOT_RESQL=http://component-byk-resql:8082
    CHATBOT_DMAPPER=http://component-byk-dmapper:3000
    CHATBOT_TIM=http://component-byk-tim:8085
    CHATBOT_OPENSEARCH=http://component-opensearch-node:9200
    CHATBOT_NOTIFICATIONS=http://component-notification-node:4040
    ANALYTICS_TIM=http://component-byk-tim:8085
    ANALYTICS_DMAPPER=http://component-byk-dmapper:3000
    ANALYTICS_RUUTER=http://component-byk-ruuter-private:8080
    ANALYTICS_RESQL=http://component-byk-resql:8082
    TRAINING_TIM=http://component-byk-tim:8085
    TRAINING_DMAPPER=http://component-byk-dmapper-v1:3000
    TRAINING_RUUTER=http://component-byk-ruuter-private:8080/training
    TRAINING_PUBLIC_RUUTER=http://component-byk-ruuter-private:8080/training
    TRAINING_RESQL=http://component-byk-resql:8082/training
    SERVICE_TIM=http://component-byk-tim:8085
    SERVICE_DMAPPER=http://component-byk-dmapper:3000
    SERVICE_RUUTER=http://component-byk-ruuter-private:8080/services
    SERVICE_RESQL=http://component-byk-resql:8082/services
    SERVICE_TRAINING_RESQL=http://component-byk-resql:8082/training/training
    TRAINING_OPENSEARCH=http://component-opensearch-node:9200
    DOMAIN=test.buerokratt.ee