imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "job-postdeploy-first-login"

user:
  login: "{{ id_code }}" # Use a test ID cde. In production replace with real ID code "Every login value must contain EE"
  first_name: "{{ first_name}}"
  last_name: "{{ last_name }}"
  id_code: "{{ id_code }}" # Use a test ID cde. In production replace with real ID code  "Every ID code value must contain EE"
  display_name: "{{ first_name }}"
  csa_email: "{{ csa_email }}"

db:
  db_host: component-databases-users-db
  db_port: "5432"
  db_user: byk
  db_password: {{ usersDB.password }} # Change password accordingly
