imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

release_name: "component-opensearch-node"  

# byk:
#   dsl:
#     image:
#       registry: "ghcr.io"
#       repository: "buerokratt/buerokratt-dsl"
#       tag: "pre-alpha-kube-1.13.64"
#   ruuter:
#     dsl:
#       path: "/script/"

images:
  scope:
    image: opensearchproject/opensearch:latest
  opensearch:
    backoffice:
      repo: https://github.com/buerokratt/Buerokratt-Chatbot.git
      path: DSL/OpenSearch
    services:
      repo: https://github.com/buerokratt/Service-Module.git
      path: DSL/OpenSearch
    training:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/OpenSearch


env:
  CLUSTER_NAME: "opensearch-cluster"
  NODE_NAME: "component-opensearch-node"
  DISCOVERY_TYPE: "single-node"
  BOOTSTRAP_MEMORY_LOCK: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
  DISABLE_INSTALL_DEMO_CONFIG: "true"
  DISABLE_SECURITY_PLUGIN: "true"
