apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.release_name }}"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Values.release_name }}"
    spec:     
      containers:
        - name: first-login
          image: alpine
          command: ["/bin/sh"]
          args: ["echo \"INSERT INTO public.user (login, first_name, last_name, id_code, display_name, status, created, csa_title, csa_email) VALUES ('{{ .Values.user.login }}', '{{ .Values.user.first_name }}', '{{ .Values.user.last_name }}', '{{ .Values.user.id_code }}', '{{ .Values.user.display_name }}', 'active', now(), '{{ .Values.user.csa_title }}', '{{ .Values.user.csa_email }}'); INSERT INTO user_authority (user_id, authority_name, created) VALUES ((SELECT id_code FROM public.user WHERE login = '{{ .Values.user.login }}'), ARRAY['ROLE_ADMINISTRATOR'], now());\" | psql"]
          env:
            - name: DB_HOST
              value: "{{ .Values.db.db_host }}"
            - name: DB_USER
              value: "{{ .Values.db.db_user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.db.db_password }}"

      restartPolicy: Never          

