apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-ruuter
spec:
  selector:
    matchLabels:
      app: byk-ruuter
  template:
    metadata:
      labels:
        app: byk-ruuter
    spec:
      containers:
        - name: byk-ruuter
          image: image: {{ .Values.images.ruuter.registry }}/{{ .Values.images.ruuter.repository }}:{{ .Values.images.ruuter.tag }}
          ports:
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: logging.level.root
              value: INFO
            - name: LOG_LEVEL_TIMING
              value: INFO
            - name: application.logging.displayRequestContent
              value: "true"
            - name: application.logging.displayResponseContent
              value: "true"
          volumeMounts:
            - name: urls-env
              mountPath: /app/constants.ini
              subPath: constants.ini
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: dsl
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
        - name: byk-dsl-services
          persistentVolumeClaim:
            claimName: byk-dsl-services
