imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name
secretname: ruuter.test.buerokratt.ee1904prod # Cert name value, change this as suited to environment

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "component-byk-ruuter-private"

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/ruuter"
    tag: "pre-alpha-2.4.1" # Images (tags) are up to date, currently no changes needed
  backoffice:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "backoffice-module-pre-alpha-1.3.13" # Images (tags) are up to date, currently no changes needed
  analytics:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "analytics-module-pre-alpha-1.4.7" # Images (tags) are up to date, currently no changes needed
  services:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "service-module-pre-alpha-1.4.6" # Images (tags) are up to date, currently no changes needed
  training:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "training-module-pre-alpha-1.4.28" # Images (tags) are up to date, currently no changes needed 
env:
  LOGGING_LEVEL_ROOT: "INFO"
  LOG_LEVEL_TIMING: "INFO"
  APPLICATION_LOGGING_DISPLAY_REQUEST_CONTENT: "false"
  APPLICATION_LOGGING_DISPLAY_RESPONSE_CONTENT: "false"
  APPLICATION_CORS_ALLOWED_ORIGINS: https://admin.test.buerokratt.ee # Change the domain name, leave subdomain and subpath same
  APPLICATION_OPENSEARCH_CONFIGURATION_URL: http://component-opensearch-node:9200
