
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: stage.buerokratt.ee # Domain name
secretname: tim.stage.buerokratt.ee3004prod  # Cert name value, change this as suited to environment
#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "component-byk-tim"
release_db: "component-databases"

byk:
  tim:
    env:
      security:
        allowlist:
          jwt: component-byk-ruuter,component-byk-ruuter-private,module-byk-widget,module-byk-authentication-layer,component-byk-tim,10.0.0.0/8,192.168.0.0/16,10.43.198.207,10.42.2.35
        oauth2:
          client:
            clientId: TARA_ID # TARA client information
            clientSecret: TARA_PASSWORD # TARA client password
            scope: openid
            userAuthorizationUri: https://tara-test.ria.ee/oidc/authorize # Change according to enviorment you deploy. Prod = tara.ria.ee Test = tara-test.ria.ee
            accessTokenUri: https://tara-test.ria.ee/oidc/token # Change according to enviorment you deploy. Prod = tara.ria.ee Test = tara-test.ria.ee
          resource:
            jwk:
              keySetUri: https://tara-test.ria.ee/oidc/jwks # Change according to enviorment you deploy. Prod = tara.ria.ee Test = tara-test.ria.ee
      legacyPortalIntegration:
        legacyUrl: NA
        legacyPortalRefererMarker: NA
        sessionCookieDomain: buerokratt.ee
      jwtIntegration:
        signature:
          issuer: stage.buerokratt.ee # Change the domain name, leave subdomain and subpath same
          keyStorePassword: ppjjpp
          keyStore: classpath:jwtkeystore.jks
      spring:
        profiles:
          active: dev
      logging:
        level:
          root: TRACE
      
tim-postgresql:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: tim
    password: "t9n5Kmm7vP9" # Change password accordingly
    database: "tim"

tim_postgresql: "t9n5Kmm7vP9"

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/tim"
    tag: "pre-apha-2.3.1" # Images (tags) are up to date, currently no changes needed

ingress:
  annotations:
    cors_origin: "https://admin.<namespace>.buerokratt.ee, https://<namespace>.buerokratt.ee, https://tim.<namespace>.buerokratt.ee, https://admin.dev.buerokratt.ee, https://ruuter.<namespace>.buerokratt.ee/, https://ruuter.<namespace>.buerokratt.ee/v2/private/, https://ruuter.<namespace>.buerokratt.ee/v2/public" 

