apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-dmapper
spec:
  selector:
    matchLabels:
      app: byk-dmapper
  template:
    metadata:
      labels:
        app: byk-dmapper
    spec:
      initContainers:
        - name: init-copy-files
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p DataMapper
              echo test.yml
              cp -r /app/DSL/DataMapper/backoffice/ /root/DSL/
              
              ls -la /root/*
          volumeMounts:
            - name: buerokratt-dsl
              mountPath: /app/DSL
            - name: dmapper-volume
              mountPath: /root/DSL/
      containers:
        - name: byk-dmapper
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          env:
            - name: EXTENSION
              value: .hbs
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: dmapper-volume
              mountPath: /DSL/

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 70
            periodSeconds: 10
      volumes:
        - name: buerokratt-dsl
          persistentVolumeClaim:
            claimName: pvc-buerokratt-dsl
        - name: dmapper-volume
          emptyDir: {}

