imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

release_name: "component-byk-resql"
release_db: "databases" # Release name - currently databases, replace wit your own release name for databases

# byk:
#   dsl:
#     image:
#       registry: "ghcr.io"
#       repository: "buerokratt/buerokratt-dsl"
#       tag: "pre-alpha-kube-1.12.33"
#   resql:
#     dsl:
#       path: "/DSL/"

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/resql"
    tag: "pre-alpha-2.4.0-27"

env:
  LOGGING_LEVEL_ROOT: "TRACE"
  SQLMS_DATASOURCES_0_NAME: "byk"
  SQLMS_DATASOURCES_0_JDBCURL: "jdbc:postgresql://databases-users-db:5432/byk"
  SQLMS_DATASOURCES_0_USERNAME: "byk"
  SQLMS_DATASOURCES_0_PASSWORD: "01234"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT: "DEBUG"
