version: '3.9'
services:

  tim-postgresql:
    container_name: tim-postgresql
    image: postgres:14.1
    environment:
      - POSTGRES_USER=tim
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=tim
    volumes:
      - tim-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bykstack

  users-db:
    container_name: users-db
    image: postgres:14.1
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=byk
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - bykstack

volumes:
  users__db:
    driver: local
  tim-db:
    driver: local
networks:
  bykstack:
    name: bykstack
    driver: bridge
    driver_opts:                         
       com.docker.network.driver.mtu: 1400
