imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod

release_name: "byk-bot"  



images:
  scope:
    bot:
      image: "riaee/byk:bot-20220728"
    bot_action: 
      image: "riaee/byk:bot-action-server-20220728"
  bot:
    dsl:
      repo: https://github.com/buerokratt/Installation-Guides.git
      path: default-setup/chatbot-and-training/bot

