
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

release_name: "component-byk-dmapper"

# byk:
#   dsl:
#     image:
#       registry: "ghcr.io"
#       repository: "buerokratt/buerokratt-dsl"
#       tag: "pre-alpha-kube-1.12.33"
#   dmapper:
#     dsl:
#       path: "/workspace/app/module"
      

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/datamapper"
    tag: "pre-alpha-2.3.1"
