apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    app: "{{ .Values.release_name }}"
  ports:
    - port: 3003
      targetPort: http
      protocol: TCP
      name: http
