apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.release_name }}-config"
data:
  development.env: |
    API_CORS_ORIGIN=*
    API_DOCUMENTATION_ENABLED=false

    S3_REGION=us-east-1
    S3_ENDPOINT_URL=
    S3_ACCESS_KEY_ID=
    S3_SECRET_ACCESS_KEY=
    S3_DATA_BUCKET_NAME=
    S3_DATA_BUCKET_PATH=

    FS_DATA_DIRECTORY_PATH=./data
