apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Value.release_name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Value.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Value.release_name }}"
    spec:
      containers:
        - name: "{{ .Value.release_name }}"
          image: "{{ .Values.images.gui.registry }}/{{ .Values.images.gui.repository }}:{{ .Values.images.gui.tag }}"
          #command: ["/bin/sh"]
          #args: ["-c", "tail -f /dev/null"]
          ports:
            - containerPort: 443
              name: http
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 34
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 34
            periodSeconds: 10
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
              #subPath: default.conf
            - name: env-config-volume
              mountPath: /usr/share/nginx/html/customer-service/env-config.js
              subPath: env-config.js
      volumes:
        - name: nginx-config-volume
          configMap:
            name: constant-config
        - name: env-config-volume
          configMap:
            name: constant-config
