imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # byk.buerokratt.ee

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer
#  certIssuerName: letsencrypt-staging 

tim-postgresql:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: tim
    password: "123"
    database: tim
  statefulset:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true

users-db:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: byk
    password: "01234"
    database: byk
  statefulset:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true

module-db:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: byk
    password: "01234"
    databases: services_db,training_db
  statefulset:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true