imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: stage.buerokratt.ee # Domain name
secretname: ruuter.stage.buerokratt.ee3004prod # Cert name value, change this as suited to environment
ingress:
  certIssuerName: letsencrypt-prod  # Change this if your certIssuerName has set up different

release_name: "component-byk-ruuter"    

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/ruuter"
    tag: "pre-alpha-2.4.1" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "backoffice-module-pre-alpha-1.3.20" # Images (tags) are up to date, currently no changes needed

env:
  LOGGING_LEVEL_ROOT: "INFO"
  LOG_LEVEL_TIMING: "INFO"
  APPLICATION_LOGGING_DISPLAY_REQUEST_CONTENT: "true"
  APPLICATION_LOGGING_DISPLAY_RESPONSE_CONTENT: "true"
  APPLICATION_CORS_ALLOWED_ORIGINS: https://admin.stage.buerokratt.ee, https://stage.buerokratt.ee, https://tim.stage.buerokratt.ee, https://ruuter.stage.buerokratt.ee # Change the domain name, leave subdomain and subpath same
