imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

release_name: "component-byk-ruuter"   

# byk:
#   dsl:
#     image:
#       registry: "ghcr.io"
#       repository: "buerokratt/buerokratt-dsl"
#       tag: "pre-alpha-kube-1.12.33"
#   ruuter:
#     dsl:
#       path: "/DSL/"
      

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/Ruuter"
    tag: "pre-alpha-2.4.1"

env:
  LOGGING_LEVEL_ROOT: "INFO"
  LOG_LEVEL_TIMING: "INFO"
  APPLICATION_LOGGING_DISPLAY_REQUEST_CONTENT: "true"
  APPLICATION_LOGGING_DISPLAY_RESPONSE_CONTENT: "true"
