---
- name: Gather Disk Space Information
  hosts: # Here goes the groupname unless you want to give each remote server specifically
  tasks:
    - name: Get disk space information
      command: df -h
      register: disk_info

    - name: Save disk space information to a file on the remote server
      copy:
        content: "{{ disk_info.stdout }}"
        dest: /tmp/disk_info.txt

    - name: Fetch the disk space information to the local machine
      fetch:
        src: /tmp/disk_info.txt
        dest: ./disk_info_{{ inventory_hostname }}.txt
