apiVersion: v1
kind: Config
clusters:
- name: "rit-byrokratt-stage"
  cluster:
    server: "https://rp-rancher.opnd.eu/k8s/clusters/c-cbgqj"
- name: "rit-byrokratt-stage-rke-2-ctrl01"
  cluster:
    server: "https://192.168.41.20:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEkwTURReU9ESXlNVEkxT0ZvWERUTTBNRFF5TmpJeU1USTFPRm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUxDV2hzQWo2TFZsCllrRE00ZUVsWkZTaHZTQ21OSjVpK1VJMkp4SVhTdGlqdmtvOHJnZFJrd\
      ndxODFBZnc3S2JlRzVxQ1FHU2p6M1AKYTl4dkpzWnZRa0ZIdXRBd2g2TEVYcXNCYm9FZkRaZlZPT\
      lVraGExbVpBZCt6dWJVRDlEVkMwcHlZTUZyRVBKOQoyRFpxdGtBalhmNlhDT01XS1NjSXRBemtYV\
      TlJbzlOWHlrYWJlQ3YwY0tMUCtyVm5XNGkzSFhUMHoxWCtnd0RHCm42WW9HRTdCeHpLRk5OM0ppU\
      Fg5aVNkZjF4SGtLSXJheEkxSjJjODFUS0F0UFNsc2FSY0hyTy9MSVl2T00yUEEKd09BY2lUR3pEa\
      jRpbW9aSnZlbll6NGpjTXM1VkI0aDIwM0crK1gvZVlyelAxbTBwRVJOTXNiSjNRRldIalIycwoxN\
      lFueDAza1lqOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGTUtZQkZycldWRWE0ZGU5cldMU2I4eFBpeGhGTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQmhPRms2S2t6VnVZRmpicnBnanVVZ0swTTIyanN5MWVUc2RUT\
      051NVg4R3B0M1M3YWxIczNJWnNJcwpSRm1XcEhkN2lRTWtBVzBsSUxQd2J0ZENNZnpmSXVZSkJ6Z\
      U5pTXR1QUwwK2JqQnJacit0V2VjZHVqdHVvMHU0CnY4ejdKTHBlN3I0UkFkZnVkeG5PVk9mQlBBQ\
      kJ2VENnT0x2YmorZ3M5U3FOdnBUTnZJYUJIT05tN0xhNlNtQisKRjBUZ3dVU2dhOUpYdlN3VGZzd\
      zRQWm5FUjJsUGlpeHVlMm1QMXkrOWJxNGRScVl3amg0MFJRWGkvaXk0ci9vZgpEVnNtYnk2R2plU\
      kdSd3lZc2RvQ3pGWnp2clZsS0t2dThaZUxwUW9UVEFvQXNudTIyZWhCZWpZZ01sNU96eXgwCndXU\
      jZSa3UvVWdXSHR2bmp3cStoZ0lPYzBzcnQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "rit-byrokratt-stage"
  user:
    token: "kubeconfig-u-c7hg45sg2s:mkmjf864j9sr8dlwzppxwgnjmwrjd6pv29vztgrgjklrkr2mkk7kwx"


contexts:
- name: "rit-byrokratt-stage"
  context:
    user: "rit-byrokratt-stage"
    cluster: "rit-byrokratt-stage"
- name: "rit-byrokratt-stage-rke-2-ctrl01"
  context:
    user: "rit-byrokratt-stage"
    cluster: "rit-byrokratt-stage-rke-2-ctrl01"

current-context: "rit-byrokratt-stage"
