apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-backoffice-gui
spec:
  selector:
    matchLabels:
      app: byk-backoffice-gui
  template:
    metadata:
      labels:
        app: byk-backoffice-gui
    spec:
      initCointainers:
        - name: copy-dsl-to-shared-storage
          image: "{{ .Values.images.dsl.registry }}/{{ .Values.images.dsl.repository }}:{{ .Values.images.dsl.tag }}"
          command: ["kubectl"]
          args:
            - "cp"
            - "Ruuter/private/v2/backoffice"
            - "/data/Ruuter/backoffice"
            - "Resql/backoffice"
            - "/data/Resql/backoffice"
            - "DataMapper/v1/backoffice"
            - "/data/DataMapper/backoffice"
      initContainers:
        - name: copy-dsl-files-to-pods
          image: bitnami/kubectl
          command: ["kubectl"]
          args:
            - "cp"
            - "/data/Ruuter/backoffice" #todo - correct paths
            - "byk-ruuter:/DSL/Ruuter/backoffice" #todo - correct paths
            - "/data/Resql"
            - "byk-resql:/DSL/Resql/backoffice"
            - "/data/DataMapper"
            - "byk-dmapper:/DSL/DataMapper/backoffice"
      containers:
        - name: byk-backoffice-gui
          image: "{{ .Values.images.gui.registry }}/{{ .Values.images.gui.repository }}:{{ .Values.images.gui.tag }}"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: REACT_APP_RUUTER_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_API_URL }}"
            - name: REACT_APP_RUUTER_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_PRIVATE_API_URL }}"
            - name: REACT_APP_BUEROKRATT_CHATBOT_URL
              value: "{{ .Values.env.REACT_APP_BUEROKRATT_CHATBOT_URL }}"
            - name: REACT_APP_MENU_URL
              value: "{{ .Values.env.REACT_APP_MENU_URL }}"
            - name: REACT_APP_MENU_PATH
              value: "{{ .Values.env.REACT_APP_MENU_PATH }}"
            - name: REACT_APP_CUSTOMER_SERVICE_LOGIN
              value: "{{ .Values.env.REACT_APP_CUSTOMER_SERVICE_LOGIN }}"
            - name: DOMAIN
              value: "{{ .Values.env.DOMAIN }}"
            - name: REACT_APP_CONVERSATIONS_BASE_URL
              value: "{{ .Values.env.REACT_APP_CONVERSATIONS_BASE_URL }}"
            - name: REACT_APP_TRAINING_BASE_URL
              value: "{{ .Values.env.REACT_APP_TRAINING_BASE_URL }}"
            - name: REACT_APP_ANALYTICS_BASE_URL
              value: "{{ .Values.env.REACT_APP_ANALYTICS_BASE_URL }}"
            - name: REACT_APP_SERVICES_BASE_URL
              value: "{{ .Values.env.REACT_APP_SERVICES_BASE_URL }}"
            - name: REACT_APP_SETTINGS_BASE_URL
              value: "{{ .Values.env.REACT_APP_SETTINGS_BASE_URL }}"
            - name: REACT_APP_MONITORING_BASE_URL
              value: "{{ .Values.env.REACT_APP_MONITORING_BASE_URL }}"
            - name: REACT_APP_SERVICE_ID
              value: "{{ .Values.env.REACT_APP_SERVICE_ID }}"
            - name: REACT_APP_NOTIFICATION_NODE_URL
              value: "{{ .Values.env.REACT_APP_NOTIFICATION_NODE_URL }}"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: menu-configmap-volume
              mountPath: /app/menu.json
              subPath: menu.json
              readOnly: true
      volumes:
        - name: menu-configmap-volume
          configMap:
            name: menu-configmap
        - name: dsl-volume
          persistentVolumeClaim:
            claimName: pvc-backoffice-dsl
