apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.release_name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.ingress.annotations.cors_origin }}"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
       add_header Content-Security-Policy "upgrade-insecure-requests; default-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'none'; style-src 'self' 'unsafe-inline'; connect-src 'self' {{ .Values.csp.connect_src }};";
  labels:
    name: "{{ .Values.release_name }}-ingress"
spec:
  rules:
    - host: admin.{{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/chat"
            backend:
              service:
                name: "{{ .Values.release_name }}"
                port:
                  number: 3001
  tls:
    - hosts:
        - admin.{{ .Values.domain }}
      secretName: {{ .Values.secretname }}
