apiVersion: v1
kind: PersistentVolume
metadata:
  name: backoffice-dsl-pv
spec:
  storageClassName: dsl
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/backoffice-dsl
