imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

#release_name: "postdeploy"
release_name: "job-postdeploy"
  
images:
  scope:
    image: opensearchproject/opensearch:latest
  pipelines:
    training:
      repo: https://github.com/buerokratt/Training-Module.git
      path: /
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "training-module-pre-alpha-1.4.25" # TODO: Change this to the correct tag

liquibase:
  jdbcUrl: "jdbc:postgresql://databases-users-db:5432/byk?user=byk"    
  dbPassword: "01234"  