version: '3.9'
services:
  dmapper:
    container_name: dmapper
    build:
      context: .
      network: host 
    ports:
      - 3000:3000
    volumes:
      - ./DSL.DMapper:/workspace/app/views/byk/
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge
    driver_opts:                         
       com.docker.network.driver.mtu: 1400
