version: '3.9'

services:

   byk-liquibase-update:
    image: liquibase/liquibase
    command: --url=jdbc:postgresql://DB_IP:5433/byk?user=byk --password= --changelog-file=/master.yml update
    ports:
      - 8000:8000
    volumes:
      - ./DSL.Liquibase/master.yml:/liquibase/master.yml
      - ./DSL.Liquibase/changelog:/liquibase/changelog
      - ./DSL.Liquibase/data:/liquibase/data
    networks:
      - bykstack
      
networks:
  bykstack:
    name: bykstack
    driver: bridge
