version: '3.9'
services:
  resql:
    container_name: resql
    build:
      context: .
      network: host
    ports:
      - 8082:8082
    volumes:
      - ./DSL.Resql:/workspace/app/templates/
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge
    driver_opts:                         
       com.docker.network.driver.mtu: 1400
