imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name
secretname: ruuter.test.buerokratt.ee1904prod #Cert name value

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod

release_name: "component-notification-node"  

# byk:
#   dsl:
#     image:
#       registry: "ghcr.io"
#       repository: "buerokratt/buerokratt-dsl"
#       tag: "pre-alpha-kube-1.13.64"
#   ruuter:
#     dsl:
#       path: "/script/"

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-chatbot"
    tag: "notification-node-pre-alpha-1.2.2"

env:
  OPENSEARCH_PROTOCOL: "http"
  OPENSEARCH_HOST: "component-opensearch-node"
  OPENSEARCH_PORT: "9200"
  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "admin"
  PORT: "4040"
  REFRESH_INTERVAL: "1000"
  CORS_WHITELIST_ORIGINS: "http://module-byk-widget:3001,http://module-byk-backoffice-gui:3000,http://component-byk-ruuter-private:8080,http://component-byk-ruuter:8080"
  RUUTER_URL: http://component-byk-ruuter:8080
  CHAT_TERMINATION_DELAY: "5000"